#!/bin/bash

# Exit on errors
set -e

dr=$1
dr_data=/pipelines-data/$dr/1
scriptpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$scriptpath/la-pipelines dwca-avro $dr
$scriptpath/la-pipelines interpret $dr
$scriptpath/la-pipelines uuid $dr
$scriptpath/la-pipelines sds $dr
#if hdfs dfs -cat "$dr_data/interpretation-metrics.yml" | grep -q multimediaRecordsCountAttempted; then
#  $scriptpath/la-pipelines image-load $dr
#  $scriptpath/la-pipelines image-sync $dr
#fi
if ! hdfs dfs -test -d "$dr_data/images"; then
  extra_args_index="--extra-args=includeImages=true"
fi
$scriptpath/la-pipelines index $dr $extra_args_index
$scriptpath/la-pipelines sample $dr
if ! hdfs dfs -test -d "$dr_data/sampling"; then
  extra_args_sample="--extra-args=includeSampling=false"
fi
$scriptpath/la-pipelines solr $dr $extra_args_sample
