- name: Install Java and la-apt
  hosts: pipelines, hadoop, spark
  become: true
  vars:
    use_openjdk11: false
    use_openjdk8: true
  roles:
    - java
    - la-apt

- name: Install hadoop
  hosts: hadoop
  become: true
  roles:
    - hadoop

- name: Install spark
  hosts: spark
  become: true
  roles:
    - spark

- name: Install pipelines
  hosts: pipelines
  become: true
  roles:
    - pipelines
