---
hadoop:
  version: 2.10.2
  hadoop_archive: hadoop-2.10.2.tar.gz
  data_dir: /var/hadoop/data
  name_dir: /var/hadoop/name
  temp_dir: /tmp/hadoop/hdfs/tmp
  download_location: https://dlcdn.apache.org/hadoop/common
  #download_location: https://archive.apache.org/dist/hadoop/common/
  user: hadoop
  user_shell: /bin/bash
  default_hosts:
    - master
    - worker
  secondary_name_node: master
  slaves:
    - master
    - worker
hadoop_install_dir: "/data/hadoop"
hadoop_master_ip: master
master_nodes: "{% if 'cluster_master' in groups %} {{ groups['cluster_master']|length }} {% else  %} 0 {% endif %}"
data_nodes: "{% if 'cluster_nodes' in groups %} {{ groups['cluster_nodes']|length }} {% else  %} 0 {% endif %}"
number_of_nodes: "{{ master_nodes + data_nodes }}"
ssh_key_filename: "hadoop_key"
install_temp_dir: "/tmp/hadoop-temp"
is_master: false
is_node: true
hdfs_replication_factor: 1
