#
# Prometheus
#
- name: Create Folder /srv/prometheus if not exist
  become: true
  file:
    path: /srv/prometheus
    mode: 0755
    state: directory

- name: Create prometheus configuration file
  become: true
  copy:
    dest: /srv/prometheus/prometheus.yml
    src: prometheus/prometheus.yml
    mode: 0644

- name: Create Prometheus container
  docker_container:
    name: prometheus
    restart_policy: always
    image: prom/prometheus:{{ prometheus_version }}
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_main_data:/prometheus
    networks:
      - name: sbdinet
    etc_hosts:
      'live-manager-1': '192.121.208.20'
      'live-solr-1': '10.65.0.154'
      'live-solr-2': '10.65.3.74'
      'live-solr-3': '10.65.2.132'
      'live-solr-4': '10.65.2.185'
      'live-cassandra-1': '10.65.3.77'
      'live-cassandra-2': '10.65.2.143'
      'live-cassandra-3': '10.65.0.229'
      'live-cassandra-4': '10.65.2.217'
      'live-solrcloud-1': '10.65.1.149'
      'live-solrcloud-2': '10.65.0.148'
      'live-solrcloud-3': '10.65.0.32'
      'live-pipelines-1': '10.65.1.173'
      'live-pipelines-2': '10.65.0.196'
      'live-pipelines-3': '10.65.1.19'
      'live-molecular-1': '192.121.208.234'
      'live-ext-1': '192.121.209.107'
      'live-pybossa': '192.121.209.239'
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.retention.time=31d
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
    published_ports: "9090:9090"

#
# Grafana
#
- name: Create Folder /srv/grafana if not exist
  become: true
  file:
    path: /srv/grafana
    mode: 0755
    state: directory

- name: Create grafana configuration files
  become: true
  copy:
    dest: /srv/
    src: grafana
    mode: 0644

- name: Create Grafana container
  docker_container:
    name: grafana
    restart_policy: always
    image: grafana/grafana:{{ grafana_version }}
    volumes:
      - grafana-data:/var/lib/grafana
      - /srv/grafana/provisioning:/etc/grafana/provisioning
      - /srv/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - name: sbdinet
    published_ports: "3000:3000"

# 
# Blackbox
#
- name: Create Blackbox container
  docker_container:
    name: blackbox
    restart_policy: always
    image: prom/blackbox-exporter:{{ blackbox_version }}
    networks:
      - name: sbdinet
    published_ports: "9115:9115"
