version: '3.7'

networks:
  basnet:
    external: true

configs:
  config_{{ app_name }}:
    file: ./config/{{ app_name }}-config.yml

services:

  bie-solr:
    image: ghcr.io/biodiversitydata-se/bie-solr:1.0.2
    environment:
      SOLR_HEAP: 4g
      SOLR_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
    volumes:
      - data_bie_solr:/var/solr
    networks:
      - basnet

  {{ app_name }}:
    image: ghcr.io/biodiversitydata-se/{{ app_name }}:{{ app_version }}
    environment:
      JAVA_OPTS: -Xmx4g -Xms128m -Xss256k -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true
    configs:
      - source: config_{{ app_name }}
        target: /data/{{ app_name }}/config/{{ app_name }}-config.yml
    networks:
      - basnet

volumes:
  data_bie_solr:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_nfs/var/volumes/data_bie_solr
