copy:
  copyPath: {{ data_dir }}/biocache-load
alaNameMatch:
  wsUrl: https://namematching.biodiversitydata.se/
sds:
  wsUrl: http://ala-sensitive-data-service:9189
collectory:
  wsUrl: https://collections.biodiversitydata.se/ws/
  httpHeaders:
    Authorization: 7cde19e0-58f4-4c3d-9205-1c4b0d2e5b1f
imageService:
  #wsUrl: https://images.biodiversitydata.se/ws/
  wsUrl: http://localhost:8082/
  httpHeaders:
    apiKey: 3cdad681-2fa4-47a1-a8d2-6ea789cf003f
speciesListService:
  wsUrl: https://lists.biodiversitydata.se
samplingService:
  wsUrl: https://spatial.biodiversitydata.se/ws/
solr:
  #zkHost: localhost:2181,localhost:2182,localhost:2183
  zkHost: solr:9983
  includeSampling: true
  numOfPartitions: 2
geocodeConfig:
  stateProvince:
    path: {{ data_dir }}/pipelines-shp/lan
    field: LnNamn
images:
  # pipe separated list (note: YAML list not coming through correctly)
  recognisedPaths: "https://images.biodiversitydata.se|http://localhost:8082"
export:
  imageServicePath: "https://images.biodiversitydata.se/image/proxyImageThumbnailLarge?imageId={0}"
locationInfoConfig:
#    countryNamesFile : /data/pipelines-data/resources/countries.txt
#    countryCentrePointsFile : /data/pipelines-data/resources/countryCentrePoints.txt
#    stateProvinceCentrePointsFile : /data/pipelines-data/resources/stateProvinceCentrePoints.txt
    stateProvinceNamesFile : {{ data_dir }}/la-pipelines/config/stateProvinces.tsv
