general:
  hdfsSiteConfig: /data/hadoop/etc/hadoop/hdfs-site.xml
  coreSiteConfig: /data/hadoop/etc/hadoop/core-site.xml

run:
  platform: spark-cluster
  spark-cluster:
    sparkMaster: spark://live-pipelines-1:7077

fs:
  platform: hdfs
  hdfs:
    fsPath: hdfs://live-pipelines-1:9000

dwca-avro:
  inputPath: /data/dwca-export/{datasetId}/{datasetId}.zip
  tempLocation: /data/dwca-export/{datasetId}/tmp/

alaNameMatch:
  wsUrl: http://localhost:9179

sds:
  wsUrl: http://localhost:9189

collectory:
  wsUrl: https://collections.biodiversitydata.se/ws/
  httpHeaders:
    Authorization: {{ pipelines.collectory_apikey }}

imageService:
  wsUrl: https://images.biodiversitydata.se/
  httpHeaders:
    apiKey: {{ pipelines.imageservice_apikey }}

speciesListService:
  wsUrl: https://lists.biodiversitydata.se

samplingService:
  wsUrl: https://spatial.biodiversitydata.se/ws/

index:
  includeImages: false

solr:
  zkHost: live-solrcloud-1:2181,live-solrcloud-2:2181,live-solrcloud-3:2181
  includeSampling: true
  numOfPartitions: 2

geocodeConfig:
  stateProvince:
    path: {{ data_dir }}/pipelines-shp/lan
    field: LnNamn

images:
  # pipe separated list (note: YAML list not coming through correctly)
  recognisedPaths: "https://images.biodiversitydata.se|http://localhost:8082"

export:
  imageServicePath: "https://images.biodiversitydata.se/image/proxyImageThumbnailLarge?imageId={0}"

locationInfoConfig:
    stateProvinceNamesFile : {{ data_dir }}/la-pipelines/config/stateProvinces.tsv

gbifConfig:
  vocabularyConfig:
    vocabulariesPath: '{fsPath}/pipelines-vocabularies/'

### la-pipelines cli additional arguments, like JVM or spark command line arguments

interpret-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-cluster:
    conf: spark.default.parallelism={{ interpret_spark_parallelism | default(16) }}
    num-executors: {{ interpret_spark_num_executors | default(6) }}
    executor-cores: {{ interpret_spark_executor_cores | default(8) }}
    executor-memory: {{ interpret_spark_executor_memory | default('24G') }}
    driver-memory: {{ interpret_spark_driver_memory | default('4G') }}

image-sync-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-cluster:
    conf: spark.default.parallelism={{ image_sync_spark_parallelism | default(16) }}
    num-executors: {{ image_sync_spark_num_executors | default(16) }}
    executor-cores: {{ image_sync_spark_executor_cores | default(8) }}
    executor-memory: {{ image_sync_spark_executor_memory | default('7G') }}
    driver-memory: {{ image_sync_spark_driver_memory | default('1G') }}

image-load-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-cluster:
    conf: spark.default.parallelism={{ image_load_spark_parallelism | default(16) }}
    num-executors: {{ image_load_spark_num_executors | default(16) }}
    executor-cores: {{ image_load_spark_executor_cores | default(8) }}
    executor-memory: {{ image_load_spark_executor_memory | default('7G') }}
    driver-memory: {{ image_load_spark_driver_memory | default('1G') }}

uuid-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    conf: spark.default.parallelism={{ uuid_spark_parallelism | default(16) }}
    num-executors: {{ uuid_spark_num_executors | default(6) }}
    executor-cores: {{ uuid_spark_executor_cores | default(8) }}
    executor-memory: {{ uuid_spark_executor_memory | default('20G') }}
    driver-memory: {{ uuid_spark_driver_memory | default('4G') }}

sampling-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }} -Dspark.master=local[*]
  spark-cluster:
    conf: spark.default.parallelism={{ sampling_spark_parallelism | default(16) }}
    num-executors: {{ sampling_spark_num_executors | default(8) }}
    executor-cores: {{ sampling_spark_executor_cores | default(8) }}
    executor-memory: {{ sampling_spark_executor_memory | default('16G') }}
    driver-memory: {{ sampling_spark_driver_memory | default('4G') }}

sensitive-sh-args:
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
    num-executors: {{ sensitive_spark_num_executors | default(8) }}
    executor-cores: {{ sensitive_spark_executor_cores | default(8) }}
    executor-memory: {{ sensitive_spark_executor_memory | default('16G') }}
    driver-memory: {{ sensitive_spark_driver_memory | default('4G') }}

sample-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}

index-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    conf: spark.default.parallelism={{ index_spark_parallelism | default(16) }}
    num-executors: {{ index_spark_num_executors | default(6) }}
    executor-cores: {{ index_spark_executor_cores | default(8) }}
    executor-memory: {{ index_spark_executor_memory | default('20G') }}
    driver-memory: {{ index_spark_driver_memory | default('4G') }}

jackknife-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    conf: spark.default.parallelism={{ jackknife_spark_parallelism | default(16) }}
    num-executors: {{ jackknife_spark_num_executors | default(24) }}
    executor-cores: {{ jackknife_spark_executor_cores | default(8) }}
    executor-memory: {{ jackknife_spark_executor_memory | default('7G') }}
    driver-memory: {{ jackknife_spark_driver_memory | default('1G') }}

clustering-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    conf: spark.default.parallelism={{ clustering_spark_parallelism | default(16) }}
    executor-memory: {{ clustering_spark_executor_memory | default('20G') }}
    driver-memory: {{ clustering_spark_driver_memory | default('4G') }}

solr-sh-args:
  local:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-embedded:
    jvm: {{ pipelines_jvm_def_options | default('-Xmx8g -XX:+UseG1GC') }}
  spark-cluster:
    conf: spark.default.parallelism={{ solr_spark_parallelism | default(200) }}
    num-executors: {{ solr_spark_num_executors | default(6) }}
    executor-cores: {{ solr_spark_executor_cores | default(8) }}
    executor-memory: {{ solr_spark_executor_memory | default('22G') }}
    driver-memory: {{ solr_spark_driver_memory | default('6G') }}
