version: '3.7'

networks:
  basnet:
    external: true

configs:
  config_{{ app_name }}:
    file: ./config/{{ app_name }}-config.yml

services:

  {{ app_name }}:
    image: ghcr.io/biodiversitydata-se/{{ app_name }}:{{ app_version }}
    environment:
      JAVA_OPTS: -Xmx16g -Xms128m -Xss256k -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true
    env_file: "/data/apps/{{ app_name }}/env/.env{{ app_name }}"
    configs:
      - source: config_{{ app_name }}
        target: /tmp/{{ app_name }}-config.yml
    command: dockerize -template /tmp/{{ app_name }}-config.yml:/data/{{ app_name }}/config/{{ app_name }}-config.yml catalina.sh run
    networks:
      - basnet
