- name: Create user with ssh key
  become: true
  ansible.builtin.user:
    name: sbdi
    password: ''
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
