version: '3.8'

networks:
  basnet:
    external: true

services:

  zookeeper-1:
    image: zookeeper:3.9
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    extra_hosts:
      - "zookeeper-1:0.0.0.0"
    networks:
      - basnet
    volumes:
      - data_zookeeper-1:/data
      - data_zookeeperlog-1:/datalog
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-1

  zookeeper-2:
    image: zookeeper:3.9
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    extra_hosts:
      - "zookeeper-2:0.0.0.0"
    networks:
      - basnet
    volumes:
      - data_zookeeper-2:/data
      - data_zookeeperlog-2:/datalog
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-2

  zookeeper-3:
    image: zookeeper:3.9
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    extra_hosts:
      - "zookeeper-3:0.0.0.0"
    networks:
      - basnet
    volumes:
      - data_zookeeper-3:/data
      - data_zookeeperlog-3:/datalog
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-3

  live-solrcloud-1:
    image: ghcr.io/biodiversitydata-se/biocache-solr:1.0.1
    environment:
      ZK_HOST: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      SOLR_HEAP: 24g
      SOLR_HOST: live-solrcloud-1
      SOLR_PORT: 8973
      SOLR_OPTS: -Dlog4j2.formatMsgNoLookups=true
    ports:
      - target: 8973
        published: 8973
        protocol: tcp
        mode: host
    networks:
      - basnet
    volumes:
      - data_solr-1:/var/solr
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-1

  live-solrcloud-2:
    image: ghcr.io/biodiversitydata-se/biocache-solr:1.0.1
    environment:
      ZK_HOST: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      SOLR_HEAP: 24g
      SOLR_HOST: live-solrcloud-2
      SOLR_PORT: 8973
      SOLR_OPTS: -Dlog4j2.formatMsgNoLookups=true
    ports:
      - target: 8973
        published: 8973
        protocol: tcp
        mode: host
    networks:
      - basnet
    volumes:
      - data_solr-2:/var/solr
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-2

  live-solrcloud-3:
    image: ghcr.io/biodiversitydata-se/biocache-solr:1.0.1
    environment:
      ZK_HOST: zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
      SOLR_HEAP: 24g
      SOLR_HOST: live-solrcloud-3
      SOLR_PORT: 8973
      SOLR_OPTS: -Dlog4j2.formatMsgNoLookups=true
    ports:
      - target: 8973
        published: 8973
        protocol: tcp
        mode: host
    networks:
      - basnet
    volumes:
      - data_solr-3:/var/solr
    deploy:
      placement:
        constraints:
          - node.hostname == live-solrcloud-3

volumes:
  data_zookeeper-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeper-1"
  data_zookeeperlog-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeperlog-1"
  data_zookeeper-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeper-2"
  data_zookeeperlog-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeperlog-2"
  data_zookeeper-3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeper-3"
  data_zookeeperlog-3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/zookeeperlog-3"
  data_solr-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/solr-1"
  data_solr-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/solr-2"
  data_solr-3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/solr-3"
