- name: Ensure configuration directories
  become: true
  file:
    path: /data/apps/{{item}}
    owner: root
    group: docker
    mode: 0775
    state: directory
  with_items:
    - "{{ app_name }}"
    - "{{ app_name }}/config"
  tags:
    - app_directory

- name: Install configuration files
  become: true
  copy:
    src : "{{ item }}"
    dest: /data/apps/{{ app_name }}/config
    owner: root
    group: docker
    mode: 0664
  with_items:
    - config/
  tags:
    - app_config

- name: Zip configuration files
  become: true
  archive:
    path: /data/apps/{{ app_name }}/config/
    dest: /data/apps/{{ app_name }}/config.zip
    format: zip
    owner: root
    group: docker
    mode: 0664
  tags:
    - app_config

- name: Install docker-compose file
  become: true
  template:
    src: docker-compose.yml
    dest: /data/apps/{{ app_name }}/docker-compose.yml
    owner: root
    group: docker
    mode: 0664
  tags:
    - deploy

- name: Deploy stack {{ app_name }}
  command: docker stack deploy -c /data/apps/{{ app_name }}/docker-compose.yml {{ app_name }}2
  tags:
    - deploy
    - deploy_service
