- name: Ensure configuration directories
  become: true
  file:
    path: /data/apps/{{item}}
    owner: root
    group: docker
    mode: 0775
    state: directory
  with_items:
    - "{{ app_name }}"
    - "{{ app_name }}/config"
  tags:
    - app_directory

- name: Install configuration files
  become: true
  copy:
    src : "{{ item }}"
    dest: /data/apps/{{ app_name }}/config
    owner: root
    group: docker
    mode: 0664
  with_items:
    - config/
  tags:
    - app_config

- name: Remove config.zip
  become: true
  file:
    state: absent
    path: /data/apps/{{ app_name }}/config.zip  
  tags:
    - app_config

- name: Zip configuration files
  become: true
  command: zip -r -j /data/apps/{{ app_name }}/config.zip /data/apps/{{ app_name }}/config
  tags:
    - app_config

- name: Install docker-compose file
  become: true
  template:
    src: docker-compose.yml
    dest: /data/apps/{{ app_name }}/docker-compose.yml
    owner: root
    group: docker
    mode: 0664
  tags:
    - deploy

#- name: Deploy stack {{ app_name }}
#  command: docker stack deploy -c /data/apps/{{ app_name }}/docker-compose.yml {{ app_name }}2
#  tags:
#    - deploy
