#- include: ../../common/tasks/setfacts.yml 


- name: "Show java version"
  debug:
    msg: "Using java versions: java8={{ use_openjdk8 }} java11={{ use_openjdk11 }}'"
  tags:
    - java

- import_tasks: openjdk-java-8.yml
  when: use_openjdk8 is defined and use_openjdk8 | bool == True

- import_tasks: openjdk-java-11.yml
  when: use_openjdk11 is defined and use_openjdk11 | bool == True
