global:
  scrape_interval: 15s

scrape_configs:

  - job_name: node-exporter
    static_configs:
    - targets: 
        - "live-manager-1:9100"
        - "live-solr-1:9100"
        - "live-solr-2:9100"
        - "live-solr-3:9100"
        - "live-solr-4:9100"
        - "live-cassandra-1:9100"
        - "live-cassandra-2:9100"
        - "live-cassandra-3:9100"
        - "live-cassandra-4:9100"
        - "live-molecular-1:9100"
        - "live-ext-1:9100"
        - "live-pybossa:9100"

  - job_name: cadvisor
    static_configs:
    - targets:
        - "live-manager-1:9101"
        - "live-solr-1:9101"
        - "live-solr-2:9101"
        - "live-solr-3:9101"
        - "live-solr-4:9101"
        - "live-cassandra-1:9101"
        - "live-cassandra-2:9101"
        - "live-cassandra-3:9101"
        - "live-cassandra-4:9101"
        - "live-ext-1:9101"
        - "live-molecular-1:9101"
        - "live-pybossa:9101"
