global:
  scrape_interval: 15s

scrape_configs:

  - job_name: node-exporter
    static_configs:
    - targets: 
        - "live-manager-1:9100"
        - "live-solr-1:9100"
        - "live-solr-2:9100"
        - "live-solr-3:9100"
        - "live-solr-4:9100"
        - "live-cassandra-1:9100"
        - "live-cassandra-2:9100"
        - "live-cassandra-3:9100"
        - "live-cassandra-4:9100"
        - "live-molecular-1:9100"
        - "live-ext-1:9100"
#        - "live-pybossa:9100"

  - job_name: cadvisor
    static_configs:
    - targets:
        - "live-manager-1:9101"
        - "live-solr-1:9101"
        - "live-solr-2:9101"
        - "live-solr-3:9101"
        - "live-solr-4:9101"
        - "live-cassandra-1:9101"
        - "live-cassandra-2:9101"
        - "live-cassandra-3:9101"
        - "live-cassandra-4:9101"
        - "live-ext-1:9101"
        - "live-molecular-1:9101"
        - "live-pybossa:9101"

  - job_name: 'blackbox-http'
    scrape_interval: 300s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: [https://api.biodiversitydata.se]
        labels:
          name: api
      - targets: [https://auth.biodiversitydata.se/apikey/]
        labels:
          name: apikey
      - targets: [https://asv-portal.biodiversitydata.se]
        labels:
          name: asv-portal
      - targets: [https://auth.biodiversitydata.se/cas/login]
        labels:
          name: auth
      - targets: [https://collections.biodiversitydata.se/ws/institution/count]
        labels:
          name: collections
      - targets: [https://ctzn.biodiversitydata.se]
        labels:
          name: ctzn
      - targets: [https://dashboard.biodiversitydata.se]
        labels:
          name: dashboard
      - targets: [https://docs.biodiversitydata.se]
        labels:
          name: docs
      - targets: [https://images.biodiversitydata.se]
        labels:
          name: images
      - targets: [https://lists.biodiversitydata.se]
        labels:
          name: lists
      - targets: [https://logger.biodiversitydata.se/service/totalsByType]
        labels:
          name: logger
      - targets: [https://mirroreum.biodiversitydata.se/auth-sign-in]
        labels:
          name: mirroreum
      - targets: ['https://records.biodiversitydata.se']
        labels:
          name: records
      - targets: ['https://records.biodiversitydata.se/ws/']
        labels:
          name: records/ws
      - targets: ['https://regions.biodiversitydata.se']
        labels:
          name: regions
      - targets: [https://sds.biodiversitydata.se]
        labels:
          name: sds
      - targets: [https://static.biodiversitydata.se]
        labels:
          name: static
      - targets: ['https://spatial.biodiversitydata.se/buildInfo']
        labels:
          name: spatial
      - targets: ['https://spatial.biodiversitydata.se/ws/buildInfo']
        labels:
          name: spatial/ws
      - targets: ['https://species.biodiversitydata.se']
        labels:
          name: species
      - targets: ['https://species.biodiversitydata.se/ws/']
        labels:
          name: species/ws
      - targets: [https://tools.biodiversitydata.se]
        labels:
          name: tools
      - targets: [https://auth.biodiversitydata.se/userdetails/]
        labels:
          name: userdetails
      - targets: [https://biodiversitydata.se]
        labels:
          name: www
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
