global:
  scrape_interval: 15s

scrape_configs:

  - job_name: node-exporter
    static_configs:
    - targets: 
        - "live-manager-1:9100"
        - "live-ext-1:9100"
        - "live-pybossa:9100"

  - job_name: cadvisor
    static_configs:
    - targets:
        - "live-manager-1:9101"
        - "live-ext-1:9101"
        - "live-pybossa:9101"
