all:
  children:
    observer:
      hosts:
        live-ext-1:
          ansible_host: 192.121.209.107
          ansible_user: ubuntu
    target:
      hosts:
        live-ext-1:
          ansible_host: 192.121.209.107
          ansible_user: ubuntu
        live-manager-1:
          ansible_host: 192.121.208.20
        live-pybossa:
          ansible_host: 192.121.209.239
          ansible_user: ubuntu
