all:
  children:
    observer:
      hosts:
        live-ext-1:
          ansible_host: 192.121.209.107
          ansible_user: ubuntu
    target:
      hosts:
        live-ext-1:
          ansible_host: 192.121.209.107
          ansible_user: ubuntu
