- name: Install aptitude using apt
  become: true
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  tags:
    - pipelines

- name: Install required system packages
  become: true
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'unzip', 'file']
  tags:
    - pipelines

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - pipelines
    - docker

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags:
    - pipelines
    - docker

- name: Update apt and install docker-ce
  become: true
  apt: update_cache=yes name={{ item }} state=latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io
  tags:
    - pipelines
    - docker

- name: Create pipelines working directories
  become: true
  file: path={{ item }} state=directory owner={{ spark_user }} group={{ spark_user }} recurse=true
  with_items:
    - "{{ data_dir }}/la-pipelines/config"
    - "{{ data_dir }}/spark-tmp"
    - "{{ data_dir }}/spark/conf"
    - "{{ data_dir }}/pipelines-shp"
    - "{{ data_dir }}/dwca-tmp"
    - "{{ data_dir }}/dwca-export"
    - "{{ data_dir }}/migration"
    - "{{ data_dir }}/pipelines-vocabularies"
  tags:
    - pipelines
    - pipelines-config

- name: Update docker directory
  become: true
  template: src={{ item }} dest=/etc/docker/daemon.json
  with_items:
    - daemon.json
  tags:
    - pipelines
    - docker

- name: Restart docker
  become: true
  service:
    name: docker
    state: restarted
  tags:
    - pipelines
    - docker

# yq is needed by the la-pipelines script

- name: Download yq
  become: true
  get_url:
    url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    dest: "/usr/bin/yq"
    mode: '0755'
  vars:
  tags:
    - pipelines
    - yq

# docopts is needed by the la-pipelines script

- name: Get docopts
  become: true
  shell: curl -o /usr/local/bin/docopts -LJO https://github.com/docopt/docopts/releases/download/v0.6.3-rc2/docopts_linux_amd64
  when: is_arm is not defined
  tags:
    - pipelines
    - docopts

- name: Make docopts executable
  become: true
  shell: chmod +x /usr/local/bin/docopts
  tags:
    - pipelines
    - docopts

- name: Install pipelines using apt
  become: true
  apt: update_cache=yes name=la-pipelines={{ pipelines_version }} force=yes
  tags:
    - pipelines
    - pipelines-apt

- name: Install pipelines config
  template: src={{ item }} dest={{ data_dir }}/la-pipelines/config/{{ item }} mode=0644 output_encoding=iso-8859-1
  with_items:
    - la-pipelines-local.yaml
  tags:
    - pipelines
    - pipelines-config

- name: Copy docker YAML files to {{ data_dir }}
  copy: src={{ item }} dest={{ data_dir }}/{{ item }}
  with_items:
    - ala-sensitive-data-service.yml
  tags:
    - pipelines
    - pipelines-services
  
- name: Copy service scripts to /usr/bin
  become: true
  copy: src={{ item }} dest=/usr/bin/{{ item }} mode=777
  with_items:
    - ala-sensitive-data-service.sh
  tags:
    - pipelines
    - pipelines-services

- name: Copy docker service files to /etc/systemd/system
  become: true
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }}
  with_items:
    - ala-sensitive-data-service.service
  tags:
    - pipelines
    - pipelines-services

#- name: Enable services
#  become: true
#  service: name={{ item }} enabled=yes
#  with_items:
#    - ala-sensitive-data-service
#  tags:
#    - pipelines
#    - pipelines-services

#- name: Start service ala-sensitive-data-service, if not running
#  become: true
#  service:
#    name: ala-sensitive-data-service
#    state: started
#  tags:
#    - pipelines
#    - pipelines-services

- name: Get Gbif API vocabularies
  run_once: true
  uri:
    url: "http://api.gbif.org/v1/vocabularies/{{ item }}/releases/latest/export"
    dest: /data/pipelines-vocabularies/{{ item }}.json
  with_items:
    - LifeStage
    - DegreeOfEstablishment
    - EstablishmentMeans
    - Pathway
  tags:
    - pipelines
    - pipelines-vocabularies

- name: Copy states file
  copy: src={{ item }} dest={{ data_dir }}/la-pipelines/config/{{ item }} mode=0644
  with_items:
    - stateProvinces.tsv
  tags:
    - pipelines
    - pipelines-states

- name: Copy and unpack SHP files (includes global layer and EEZ derived from GBIFs geocode DB)
  unarchive:
    src: "{{ item }}"
    dest: "{{ data_dir }}/pipelines-shp"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
  with_items:
    - pipelines-shp.zip
  tags:
    - pipelines
    - pipelines-layers
