version: '3.7'

networks:
  basnet:
    external: true

configs:
  config_specieslist-webapp:
    file: "/data/apps/{{ app_name }}/config/{{ app_name }}-config.properties"
  logback_specieslist-webapp:
    file: "/data/apps/{{ app_name }}/config/logback.xml"

services:
  {{ app_name }}:
    image: ghcr.io/biodiversitydata-se/specieslist-webapp:{{ app_version }}
    environment:
      JAVA_OPTS: -Xmx4g -Xms128m -Xss256k -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true
    env_file: "/data/apps/{{ app_name }}/env/.env{{ app_name }}"
    configs:
      - source: config_specieslist-webapp
        target: /tmp/{{ app_name }}-config.properties
      - source: logback_specieslist-webapp
        target: /data/{{ app_name }}/config/logback.xml     
    volumes:
      - data_nameindex:/data/lucene/namematching
    command: dockerize -wait tcp://mysqldb-{{ app_name }}:3306 -timeout 60s -template /tmp/{{ app_name }}-config.properties:/data/{{ app_name }}/config/{{ app_name }}-config.properties catalina.sh run
    networks:
      - basnet

  mysqldb-specieslist-webapp:
    image: mysql:5.7
    environment:
      LANG: C.UTF-8
    env_file: "/data/apps/{{ app_name }}/env/.env{{ app_name }}"
    command: --sql_mode=""
    volumes:
 #     - ./initdb.d:/docker-entrypoint-initdb.d
      - db_data_specieslists:/var/lib/mysql
    networks:
      - basnet

volumes:
  db_data_specieslists:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=live-manager-1,rw
      device: ":/docker_nfs/var/volumes/db_data_specieslists"
  data_nameindex:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=live-manager-1,rw
      device: ":/docker_nfs/var/volumes/data_nameindex"
