- name: Deploy app
  vars:
    app_hosts:
      apikey: ext_server
      userdetails: ext_server
      ala-cas-5: ext_server
  vars_prompt:
  - name: app_name
    prompt: App name
    private: false
  - name: app_version
    prompt: App version
    private: false
  hosts: "{{ app_hosts[app_name] | default('swarm_managers') }}"

  tasks:

    - name: Ensure main apps directory
      become: true
      file:
        path: /{{ item }}
        owner: root
        group: root
        mode: 0755
        state: directory
      with_items:
        - data
        - data/apps
      tags:
        - app_directory

    - name: Deploy {{ app_name }} {{ app_version }}
      include_role:
        name: "../roles/apps/{{ app_name }}"
      tags:
        - deploy
        - app_config
