- name: Deploy Dashboard
  hosts: swarm_managers
  become: true
  vars_prompt:
    - name: app_version
      prompt: Version
      private: false
  roles:
    - ../roles/docker_apps/dashboard
  tags:
    - dashboard
  