- name: Install Observability stack (targets)
  hosts: monitoring_target
  become: true
  tags:
    - target
  roles:
    - ../roles/monitoring/target

- name: Install Observability stack (observer)
  hosts: monitoring_observer
  become: true
  tags:
    - observer
  roles:
    - ../roles/monitoring/observer
